#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo "Missing target directory"
    echo "Usage: $(basename "$0") <directory>"
    exit 22
fi

if [[ ! -d "$(pwd)/.git" ]]; then
    echo "$(pwd) is not a git repository or not the root of one"
    exit 2
fi

if [[ -d "$1" ]]; then
    echo "$1 exists and will be moved to $1.old"
    mv "$1" "$(dirname "$1")/$(basename "$1")".old
    git add -u "$1"
    git commit -m "[subtree] $(dirname "$1")/$(basename "$1")"
fi

repo="$(basename "$1")"
git subtree add --prefix="$1" ssh://git@gitlab.archlinux.org/archlinux/packaging/packages/"$repo".git main

