#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo "Missing target directory"
    echo "Usage: $(basename "$0") <directory>"
    exit 22
fi

if [[ ! -d "$1" ]]; then
    echo "$1 does not exist or not a directory"
    exit 2
fi

if [[ ! -d "$(pwd)/.git" ]]; then
    echo "$(pwd) is not a git repository or not the root of one"
    exit 2
fi

repo="$(basename "$1")"
git subtree pull --prefix="$1" --squash ssh://aur@aur.archlinux.org/"$repo".git master
