name: abaddon

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/abaddon/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: aur/abaddon
      repository: ${{ matrix.repository }}
