name: arenatracker

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/arenatracker/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/arenatracker
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
