name: arenatracker-git

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/arenatracker-git/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: public/arenatracker-git
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
