name: ccache-ext

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/ccache-ext/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: aur/ccache-ext
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
