
name: conky

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - extra/conky/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: extra/conky
      repository: ${{ matrix.repository }}
