name: dhewm3

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 */7 * *'
  push:
    branches:
     - master
    paths:
     - aur/dhewm3/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: aur/dhewm3
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      makepkg_args: -p PKGBUILD.live
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: aur/dhewm3
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.live
      release_tag: loathk-personal
