name: dxvk-mingw

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/dxvk-mingw/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
          - repository: personal
            pkgbuild: PKGBUILD.personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/dxvk-mingw
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
