name: dxvk-nvapi-mingw-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 */3 * *'
  push:
    branches:
     - master
    paths:
     - public/dxvk-nvapi-mingw-git/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/dxvk-nvapi-mingw-git
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
