name: dxvk-mingw

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/dxvk-mingw/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/dxvk-mingw
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/dxvk-mingw
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.personal
      release_tag: loathk-personal
