name: dxvk-nvapi-mingw-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 */3 * *'
  push:
    branches:
     - master
    paths:
     - public/dxvk-nvapi-mingw-git/.SRCINFO
     - .github/workflows/dxvk-nvapi-mingw-git.yml

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            action: build
          - repository: personal
            action: remove
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/dxvk-nvapi-mingw-git
      repository: ${{ matrix.repository }}
      action: ${{ matrix.action }}
