name: dxvk-mingw-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */3 * *'
  push:
    branches:
     - master
    paths:
     - local/dxvk-mingw-git/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: local/dxvk-mingw-git
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: local/dxvk-mingw-git
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.personal
      release_tag: loathk-personal
