name: dxvk-nvapi-mingw-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 */3 * *'
  push:
    branches:
     - master
    paths:
     - public/dxvk-nvapi-mingw-git/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
          - repository: personal
            pkgbuild: PKGBUILD.personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/dxvk-nvapi-mingw-git
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
