
name: gamescope-hasvk

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
    paths:
     - extra/gamescope-hasvk/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
          - repository: personal
            pkgbuild: PKGBUILD
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: extra/gamescope-hasvk
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
      pkgbuild: ${{ matrix.pkgbuild }}
