name: java21-jetbrains

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/java21-jetbrains/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: aur/java21-jetbrains
      repository: ${{ matrix.repository }}
