name: lgogdownloader-qt5

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/lgogdownloader-qt5/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: aur/lgogdownloader-qt5
      repository: ${{ matrix.repository }}
