
name: minio

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
          - 'build'
          - 'remove'
          - 'skip'
  push:
    branches:
      - master
    paths:
      - extra/minio/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: extra/minio
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
