name: nvm

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/nvm/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
          - repository: personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: aur/nvm
      repository: ${{ matrix.repository }}
      action: skip
