name: opencv2

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - aur/opencv2/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/_job_pkgbuild.yml
    with:
      pkgdir: aur/opencv2
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
