name: pcsx2-git

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */7 * *'
  push:
    branches:
     - master
    paths:
     - local/pcsx2-git/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        repository: [public, personal]
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: local/pcsx2-git
      repository: ${{ matrix.repository }}
