name: pkgbuild

on:
  workflow_call:
    inputs:
      pkgdir:
        required: true
        type: string
      makepkg_args:
        required: false
        type: string
      multilib:
        required: false
        type: boolean
      repo:
        required: true
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure public
      if: ${{ inputs.repo == 'public' }}
      id: configure
      run: |
        echo "pacman_conf=.github/conf/public_pacman.conf" >> $GITHUB_OUTPUT
        echo "makepkg_conf=.github/conf/public_makepkg.conf" >> $GITHUB_OUTPUT
        echo "release_tag=loathk-public" >> $GITHUB_OUTPUT

    - name: Configure personal
      if: ${{ inputs.repo == 'personal' }}
      id: configure
      run: |
        echo "pacman_conf=.github/conf/personal_pacman.conf" >> $GITHUB_OUTPUT
        echo "makepkg_conf=.github/conf/personal_makepkg.conf" >> $GITHUB_OUTPUT
        echo "release_tag=loathk-personal" >> $GITHUB_OUTPUT

    - name: Prepare Cache
      uses: actions/cache@v3
      with:
        path: ./.ccache
        key: ${{ github.workflow }}-${{ steps.configure.outputs.release_tag }}-${{ github.run_id }}
        restore-keys: |
          ${{ github.workflow }}-${{ steps.configure.outputs.release_tag }}

    - name: Run 'pkgbuild' action
      id: pkgbuild
      uses: ./.github/actions/pkgbuild
      with:
        pkgdir: ${{ inputs.pkgdir }}
        pacmanConf: ${{ steps.configure.outputs.pacman_conf }}
        makepkgConf: ${{ steps.configure.outputs.makepkg_conf }}
        makepkgArgs: ${{ inputs.makepkg_args }}
        multilib: ${{ inputs.multilib == 'true' }}
        repoReleaseTag: ${{ steps.configure.outputs.release_tag }}

    - name: Print Package Files
      run: |
        echo "* Successfully created the following package archives"
        echo "    New Package: ${{ steps.pkgbuild.outputs.pkgfile0 }}"
        echo "    New Package: ${{ steps.pkgbuild.outputs.pkgfile1 }}"
        echo "    New Package: ${{ steps.pkgbuild.outputs.pkgfile2 }}"
        echo "    New Package: ${{ steps.pkgbuild.outputs.pkgfile3 }}"
        echo "* Replacing these archives in the repository"
        echo "    Old Package: ${{ steps.pkgbuild.outputs.oldfile0 }}"
        echo "    Old Package: ${{ steps.pkgbuild.outputs.oldfile1 }}"
        echo "    Old Package: ${{ steps.pkgbuild.outputs.oldfile2 }}"
        echo "    Old Package: ${{ steps.pkgbuild.outputs.oldfile3 }}"
        echo "* Repository database files"
        echo "    Repo: ${{ steps.pkgbuild.outputs.repofile0 }}"
        echo "    Repo: ${{ steps.pkgbuild.outputs.repofile1 }}"
        echo "    Repo: ${{ steps.pkgbuild.outputs.repofile2 }}"
        echo "    Repo: ${{ steps.pkgbuild.outputs.repofile3 }}"

    - name: Publish to Repository
      uses: ./.github/actions/publish
      with:
        release_tag: ${{ inputs.release_tag }}
        files: '[ "${{ steps.pkgbuild.outputs.pkgfile0 }}", "${{ steps.pkgbuild.outputs.pkgfile1 }}", "${{ steps.pkgbuild.outputs.pkgfile2 }}", "${{ steps.pkgbuild.outputs.pkgfile3 }}"]'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Repository Database
      uses: ./.github/actions/publish
      with:
        release_tag: ${{ inputs.release_tag }}
        files: '[ "${{ steps.pkgbuild.outputs.repofile0 }}", "${{ steps.pkgbuild.outputs.repofile1 }}", "${{ steps.pkgbuild.outputs.repofile2 }}", "${{ steps.pkgbuild.outputs.repofile3 }}"]'
        token: ${{ secrets.GITHUB_TOKEN }}
