name: proton

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/proton/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
          - repository: personal
            pkgbuild: PKGBUILD.personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: public/proton
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: true
