name: proton-ge-custom [personal]

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/proton-ge-custom/.SRCINFO

jobs:
  personal:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/proton-ge-custom
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.testing
      multilib: true
      release_tag: loathk-personal
