name: proton-ge-custom7

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/proton-ge-custom7/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
          - repository: personal
            pkgbuild: PKGBUILD.personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      path: local/proton-ge-custom7
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
      action: build
