name: proton-ge-custom7

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/proton-ge-custom7/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: local/proton-ge-custom7
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      multilib: true
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: local/proton-ge-custom7
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.personal
      multilib: true
      release_tag: loathk-personal
