name: python-wordninja

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/python-wordninja/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/_job_pkgbuild.yml
    with:
      pkgdir: public/python-wordninja
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
