name: rare

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/rare/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: local/rare
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
