name: rare-git

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - local/rare-git/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/job_pkgbuild.yml
    with:
      pkgdir: local/rare-git
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
