name: vitables

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/vitables/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/_job_pkgbuild.yml
    with:
      pkgdir: public/vitables
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      release_tag: loathk-public
