name: wine-staging

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - multilib/wine-staging/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
          - repository: personal
            pkgbuild: PKGBUILD.personal
    uses: ./.github/workflows/job_pkgrepo.yml
    with:
      pkgdir: multilib/wine-staging
      multilib: true
      repository: ${{ matrix.repository }}
      pkgbuild: ${{ matrix.pkgbuild }}
