name: wine-staging

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - multilib/wine-staging/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: multilib/wine-staging
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      makepkg_args: --skippgpcheck
      multilib: true
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/pkgbuild.yml
    with:
      pkgdir: multilib/wine-staging
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: --skippgpcheck -p PKGBUILD.personal
      multilib: true
      release_tag: loathk-personal
