name: wine-ge-custom

on:
  workflow_dispatch:
  push:
    branches:
     - master
    paths:
     - public/wine-ge-custom/.SRCINFO

jobs:
  public:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/wine-ge-custom
      pacman_conf: .github/conf/public_pacman.conf
      makepkg_conf: .github/conf/public_makepkg.conf
      multilib: true
      release_tag: loathk-public
  personal:
    uses: ./.github/workflows/workflow.yml
    with:
      pkgdir: public/wine-ge-custom
      pacman_conf: .github/conf/personal_pacman.conf
      makepkg_conf: .github/conf/personal_makepkg.conf
      makepkg_args: -p PKGBUILD.testing
      multilib: true
      release_tag: loathk-personal
