
name: wine-cachyos-opt

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
        - 'build'
        - 'remove'
        - 'skip'
  push:
    branches:
     - master
    paths:
     - public/wine-cachyos-opt/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD
            multilib: false
          - repository: personal
            pkgbuild: PKGBUILD
            multilib: false
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: public/wine-cachyos-opt
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
