
name: wine-staging

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Repository action"
        required: true
        type: choice
        default: 'build'
        options:
          - 'build'
          - 'remove'
          - 'skip'
  push:
    branches:
      - master
    paths:
      - multilib/wine-staging/.SRCINFO

jobs:
  repository:
    strategy:
      matrix:
        include:
          - repository: public
            pkgbuild: PKGBUILD.wow64
            multilib: false
          - repository: personal
            pkgbuild: PKGBUILD.wow64
            multilib: false
    uses: ./.github/workflows/_job_pkgrepo.yml
    with:
      pkgdir: multilib/wine-staging
      repository: ${{ matrix.repository }}
      action: ${{ inputs.action != '' && inputs.action || 'build' }}
      pkgbuild: ${{ matrix.pkgbuild }}
      multilib: ${{ matrix.multilib }}
