name: Package

on:
  workflow_call:
    inputs:
      pkgdir:
        required: true
        type: string
      pacman_conf:
        required: true
        type: string
      makepkg_conf:
        required: true
        type: string
      makepkg_args:
        required: false
        type: string
      multilib:
        required: false
        type: boolean
      release_tag:
        required: true
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Makepkg Build and Check
      id: makepkg
      uses: loathingkernel/pkgbuild-action@master
      with:
        pkgdir: ${{ inputs.pkgdir }}
        pacmanConf: ${{ inputs.pacman_conf }}
        makepkgConf: ${{ inputs.makepkg_conf }}
        makepkgArgs: ${{ inputs.makepkg_args }}
        multilib: ${{ inputs.multilib == 'true' }}
        repoReleaseTag: ${{ inputs.release_tag }}

    - name: Print Package Files
      run: |
        echo "* Successfully created the following package archives"
        echo "    New Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "    New Package: ${{ steps.makepkg.outputs.pkgfile1 }}"
        echo "    New Package: ${{ steps.makepkg.outputs.pkgfile2 }}"
        echo "    New Package: ${{ steps.makepkg.outputs.pkgfile3 }}"
        echo "* Replacing these archives in the repository"
        echo "    Old Package: ${{ steps.makepkg.outputs.remfile0 }}"
        echo "    Old Package: ${{ steps.makepkg.outputs.remfile1 }}"
        echo "    Old Package: ${{ steps.makepkg.outputs.remfile2 }}"
        echo "    Old Package: ${{ steps.makepkg.outputs.remfile3 }}"
        echo "* Repository database files"
        echo "    Repo: ${{ steps.makepkg.outputs.repofile0 }}"
        echo "    Repo: ${{ steps.makepkg.outputs.repofile1 }}"
        echo "    Repo: ${{ steps.makepkg.outputs.repofile2 }}"
        echo "    Repo: ${{ steps.makepkg.outputs.repofile3 }}"

    - name: Publish to Repository
      uses: ./.github/actions/publish
      with:
        release_tag: ${{ inputs.release_tag }}
        files: '[ "${{ steps.makepkg.outputs.pkgfile0 }}", "${{ steps.makepkg.outputs.pkgfile1 }}", "${{ steps.makepkg.outputs.pkgfile2 }}", "${{ steps.makepkg.outputs.pkgfile3 }}"]'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Repository Database
      uses: ./.github/actions/publish
      with:
        release_tag: ${{ inputs.release_tag }}
        files: '[ "${{ steps.makepkg.outputs.repofile0 }}", "${{ steps.makepkg.outputs.repofile1 }}", "${{ steps.makepkg.outputs.repofile2 }}", "${{ steps.makepkg.outputs.repofile3 }}"]'
        token: ${{ secrets.GITHUB_TOKEN }}
